### PR TITLE
enable FTS5

### PR DESCRIPTION
**Pull request by mkuhn**
Since SQLite 3.9, the FTS5 extension is also available. This flag switches it on.

### CODE REVIEW

**Comment by krlmlr** [comment]
Could you please submit the PR against the main repo in rstats-db? https://github.com/rstats-db/RSQLite

FTS = full-text search? What are the implications?

**Comment by mkuhn** [comment]
The main repo doesn't have the new SQLite version, therefore I opened the PR against your 3.9 branch. 

Yes, FTS5 is full text search -- like FTS3 that is already enabled in the original version. I don't see any implications beyond making this extension available in the linked version.

**Comment by krlmlr** [comment]
Oh, I see. Thanks.

There's a new SQLite release twice a week or so, I wonder what's the best strategy to handle this. Given the insane test suite they have, it's probably safe to use any of these, and perhaps even download during installation.

**Comment by mkuhn** [comment]
Updating the SQLite sources upon installation sounds like a recipe for trouble, even if it should be okay in the vast majority of cases. The current flurry of updates seems to be caused by bugs discovered in 3.10.0. So in general updating every few months should be fine. 

(The release in the main branch, 3.8.8.2, is one year old.)

**Comment by krlmlr** [comment]
Could you please merge/rebase the base branch again, so that the Travis tests can run?

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
